# Generated by Django 5.2.8 on 2025-11-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='palavras_chave',
            field=models.TextField(blank=True, default='', help_text='Liste todos os termos de busca (Ex: Bolo, Brigadeiro, Cimento, Tinta)', verbose_name='Palavras-Chave/Tags'),
        ),
    ]
