# Generated by Django 5.2.8 on 2025-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
