# Generated by Django 5.2.8 on 2025-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, help_text='Ex: Pedreiro, Carpinteiro, Barbeiro...', max_length=100, null=True, verbose_name='Profissão principal'),
        ),
    ]
