# Generated by Django 5.2.8 on 2025-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Opcional — MEI ou empresa.', max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='palavras_chave',
            field=models.TextField(blank=True, default='', help_text='Ex: Pedreiro, Pintor, Eletricista…', verbose_name='Palavras-Chave/Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, help_text='Ex: Pedreiro, Carpinteiro, Barbeiro…', max_length=100, null=True, verbose_name='Profissão principal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(default=False, help_text='Define se o usuário será tratado como prestador de serviços.', verbose_name='É Profissional?'),
        ),
    ]
