# Generated by Django 5.2.8 on 2025-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_cnpj_alter_profile_palavras_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_professional_setup',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já passou pela triagem inicial de profissional'),
        ),
    ]
