# Generated by Django 5.2.8 on 2025-12-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_has_completed_professional_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_completed_professional_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='palavras_chave',
            field=models.TextField(blank=True, default='', verbose_name='Palavras-Chave/Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão principal'),
        ),
    ]
