# Generated by Django 5.2.8 on 2025-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_portfolioitem_file_alter_profile_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='palavras_chave',
            field=models.TextField(blank=True, default='', help_text='Ex: Pedreiro, Pintor, Eletricista', verbose_name='Palavras-Chave/Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Avaliação Média'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Endereço de e-mail'),
        ),
    ]
