# Generated by Django 5.2.8 on 2025-11-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Demanda')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP do Serviço')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_professional': False}, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_criadas', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, limit_choices_to={'is_professional': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_aceitas', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='app_servicos.service')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Avaliação')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_professional': False}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_feitos', to=settings.AUTH_USER_MODEL)),
                ('demanda', models.OneToOneField(help_text='A Demanda que gerou o feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_servicos.demanda')),
                ('professional', models.ForeignKey(limit_choices_to={'is_professional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Proposto')),
                ('proposta_prazo', models.CharField(max_length=50, verbose_name='Prazo Sugerido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status da Oferta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app_servicos.demanda')),
                ('professional', models.ForeignKey(limit_choices_to={'is_professional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'unique_together': {('demanda', 'professional')},
            },
        ),
    ]
