# Generated by Django 5.2.8 on 2025-12-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0002_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='demands/audio/'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='localizacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cidade e UF'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='orcamento_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='demands/photos/'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='demands/videos/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='demanda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_servicos.demanda'),
        ),
    ]
