# Generated by Django 5.2.8 on 2025-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0003_demanda_audio_demanda_data_limite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='data_limite',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='orcamento_estimado',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='video',
        ),
        migrations.AddField(
            model_name='demanda',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='demandas/photos/'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='demandas/videos/'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='proposta_prazo',
            field=models.CharField(max_length=50, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='proposta_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status Oferta'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='🛠️', max_length=50, verbose_name='Ícone'),
        ),
    ]
